# Generated by Django 3.2.16 on 2022-10-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50, unique=True)),
                ('computer_score', models.IntegerField(default=0)),
                ('user_score', models.IntegerField(default=0)),
            ],
        ),
    ]
